### ISSUE TITLE
Fail to put gitblame in lualine.

### ISSUE THREAD

**Issue by CharlesChiuGit** [f-person/git-blame.nvim#51]
Error message:
```txt
Error executing lua ...im/autoload/plugged/git-blame.nvim/lua/gitblame/init.lua:260: attempt to index upvalue 'date_for│~
mat' (a nil value)                                                                                                            │~
stack traceback:                                                                                                              │~
        ...im/autoload/plugged/git-blame.nvim/lua/gitblame/init.lua:260: in function 'init'                                   │~
        [string ":lua"]:1: in main chunk
```

My gitblame.lua config:
```lua
local status, git_blame = pcall(require, "gitblame")
if (not status) then return end


-- Disable virtual text
vim.g.gitblame_display_virtual_text = 0

vim.g.gitblame_date_format = '%Y-%m-%d %H:%M:%S'

require('lualine').setup({
  sections = {
    lualine_c = {
      { git_blame.get_current_blame_text, cond = git_blame.is_blame_text_available }
  }
  }
})
```

Neovim version: 
```txt
NVIM v0.8.0-dev+374-ge13dcdf16
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

OS: `Ubuntu22.04 on wsl2`

---

I also tried to comment the `vim.g.gitblame_date_format`, but the error remains.

**Comment by f-person** [comment]
It seems that `vim.g.gitblame_date_format` is `nil` for some reason. What happens if you remove `vim.g.gitblame_date_format = '%Y-%m-%d %H:%M:%S'`?

**Comment by CharlesChiuGit** [comment]
The result is a bit different this time.

Error message:
```txt
                    Error detected while processing function GitBlameInit:                                                    │~
line    5:                                                                                                                    │~
E5108: Error executing lua ...im/autoload/plugged/git-blame.nvim/lua/gitblame/init.lua:260: attempt to index upvalue 'date_for│~
mat' (a nil value)                                                                                                            │~
stack traceback:                                                                                                              │~
        ...im/autoload/plugged/git-blame.nvim/lua/gitblame/init.lua:260: in function 'init'                                   │~
        [string ":lua"]:1: in main chunk
 ```

I completely remove `vim.g.gitblame_date_format` this time.
```lua
local status, git_blame = pcall(require, "gitblame")
if (not status) then return end


-- Disable virtual text
vim.g.gitblame_display_virtual_text = 0

require('lualine').setup({
  sections = {
    lualine_c = {
      { git_blame.get_current_blame_text, cond = git_blame.is_blame_text_available }
  }
  }
})
```

So the problem seems to related to disabling virtual text?

**Comment by f-person** [comment]
> So the problem seems to related to disabling virtual text?

I don't think so. `gitblame_display_virtual_text` only controls whether or not virtual text is enabled and doesn't involve modification of the logic

**Comment by f-person** [comment]
I just tried your config on my machine/setup and it... works fine. Maybe you're somehow overriding `g.gitblame_date_format` somewhere?

**Comment by f-person** [comment]
Ooops, catched it! Thanks for the report, will check it.

It seems that the issue exists when setting the config from Lua

**Comment by f-person** [comment]
Should be fixed now :3

**Comment by CharlesChiuGit** [comment]
Thanks for the quick fix!
But it seems the gitblame message is still not showing in lualine. 🥲
![image](https://user-images.githubusercontent.com/32497323/173957534-767241e6-f239-4896-8dfb-af6ddf13226d.png)

**Comment by f-person** [comment]
Hmm, I cannot reproduce it this time. Maybe this is an issue in a specific repo?

**Comment by CharlesChiuGit** [comment]
Hmm, that me restart my wsl and redo everything again.

**Comment by CharlesChiuGit** [comment]
Yaha! Found it! Somehow I have to add `vim.g.gitblame_enable = 1` to make it valid to the lualine.

Big thanks to your quick fix and your help!

![image](https://user-images.githubusercontent.com/32497323/173958788-09fdfe62-b1cd-4d04-acfe-f20ce2d168e2.png)

**Comment by f-person** [comment]
Glad to hear it works now! ✨
